dist: xenial
language: python
os: linux
sudo: required

python:
- "3.6"

env:
- CHANGE_MINIKUBE_NONE_USER=true DISTRO_TYPE=upstream

install:
- ./scripts/ci/install-deps

before_script:
- kind create cluster

jobs:
  include:
  - name: Install Operator
    script:
    - export KUBECONFIG="$(kind get kubeconfig-path)"
    - kubectl create namespace mongodb
    - kubectl apply -f crds.yaml
    - kubectl apply -f mongodb-enterprise.yaml
    - sleep 10
    - echo "Pods in the namespace"
    - kubectl -n mongodb get pods -o yaml
    - echo "Deployments in the namespace"
    - kubectl -n mongodb get deployments -o yaml
