dist: xenial
language: python
os: linux
sudo: required

python:
- "3.6"

install:
- ./scripts/ci/install-deps

before_script:
- sudo minikube start --memory=4096 --vm-driver=none --kubernetes-version="v1.14.0" --extra-config=apiserver.v=10
- sudo chown -R $USER ${HOME}/.{mini,}kube
- kubectl config use-context minikube

jobs:
  include:
  - name: Run simple tests
    script:
    - kubectl create namespace mongodb
    - kubectl apply -f crds.yaml
    - kubectl apply -f mongodb-enterprise.yaml
    - kubectl -n mongodb logs $(kubectl -n mongodb get pods -o name)

  - name: Run simple test 2 (how does the jobs work?)
    script:
    - echo "this is another job"
