#!/usr/bin/env bash

sudo apt-get update -yq
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" -yq

sudo apt-get update -yq
sudo apt-cache policy docker-ce
sudo apt-get install -y docker-ce
