#!/usr/bin/env bash

SUDO=sudo

echo "Installing kubectl"
KUBE_VER="v1.14.0"
curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/${KUBE_VER}/bin/linux/amd64/kubectl"
chmod +x kubectl
$SUDO mv kubectl /usr/local/bin/

# minikube and crictl dependency
echo "Installing minikube and crictl"
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube
$SUDO mv minikube /usr/local/bin/
